# yaml-language-server: $schema=mkdocs.schema.json
---
site_name: procclean
site_url: !ENV [CF_URL, SITE_URL, ""]
site_description: Interactive TUI for exploring and cleaning up processes
site_author: Kaj Kowalski

repo_name: kjanat/procclean
repo_url: https://github.com/kjanat/procclean

edit_uri: edit/master/docs/

docs_dir: ../docs
site_dir: out

dev_addr: "0.0.0.0:8000"

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: procclean/icon
  favicon: assets/images/favicon.svg
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.action.view
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.path
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - privacy:
      enabled: !ENV [CI, false]
      links: true
      links_noopener: true
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        background_color: "#454444"
        color: "#54ebdd"
  - optimize:
      enabled: !ENV [CI, false]
      optimize_png: !ENV [PNGQUANT, true]

nav:
  - Home:
      - index.md
      - Installation: installation.md
  - CLI:
      - Reference: cli.md
      - Examples: examples.md
  - TUI:
      - Guide: tui.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - tables

hooks:
  - hooks/ensure_cli_docs.py
  - hooks/ensure_screenshots.py
  - hooks/robots_txt.py

watch:
  - includes
  - ../docs

extra:
  generator: false
  private: !ENV [PRIVATE, false] # Set PRIVATE=true to block indexing
  homepage: !ENV [CF_URL, SITE_URL, ""]

extra_css:
  - stylesheets/extra.css
