# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
---
site_name: procclean
site_url: !ENV SITE_URL
site_description: Interactive TUI for exploring and cleaning up processes
site_author: Kaj Kowalski

repo_name: kjanat/procclean
repo_url: https://github.com/kjanat/procclean

docs_dir: ../docs
site_dir: out

dev_addr: "0.0.0.0:8000"

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: procclean/icon
  favicon: assets/favicon.svg
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - privacy:
      links: true
      links_noopener: true
  - social:
      cards_layout_options:
        background_color: "#454444"
        color: "#54ebdd"
  - typeset
  - optimize:
      optimize_png: !ENV [PNGQUANT, true]

nav:
  - Home: index.md
  - Installation: installation.md
  - CLI Reference: cli.md
  - TUI Guide: tui.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - tables

watch:
  - includes

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
